### PR TITLE
[RFC] Introduce PresburgerSet

### PR DESCRIPTION
**Pull request by multiverstack-intellif**
This RFC proposes to introduce PresburgerSet as another integer set utility, aiming to tackle more complex analysis problems.
[rendered](https://github.com/multiverstack-intellif/tvm-rfcs/blob/improve_intset/rfcs/0099-introduce-PresburgerSet.md)

cc @wrongtest-intellif @Hzfengsy @spectrometerHBH @tqchen

### CODE REVIEW

**Comment by tqchen** [comment]
Thank you for the proposal. There is a general tradeoff in terms between speed of solving, generality of the solution, and extra capabilities(eg ability to handle symbolic division/mod that may go beyond normal).

The current hyperbox based analysis was chosen because of its speed efficiency, of course that also comes with limitations. Additionally, there is a relaxation in analysis so to handle arithmetics that may not be exactly captured by intset.

Normal constraint solver based solution might come with some extra capabilities, the question here being whether the efficiency can be kept up. 

My recommendation would be to start with a different class first under arith for us to understand the overall space. Likely fewer passes will need such analysis, then we go from there

**Comment by tqchen** [comment]
To get extra clarity, we could rename the current IntSet explicitly as IntervalSet.

**Comment by multiverstack-intellif** [comment]
@tqchen Thanks for you recommendation. Agree with the efficiency risk and it's now updated. Could you take another look?

**Comment by tqchen** [comment]
Thank you @multiverstack-intellif i think it is a good starting pt. We can iterate on APIs and other things as we start improving the overall toolset

**Review by tqchen — APPROVED** [review]

**Review by Hzfengsy — APPROVED** [review]

**Comment by Hzfengsy** [comment]
Let's keep it open for one week for enough visibility 😄

**Review by vinx13 — APPROVED** [review]

**Comment by multiverstack-intellif** [comment]
> 



> I very much like the proposed improvements, especially the use cases for inner-block and inter-block analysis. While I have made some development [for similar applications](https://github.com/apache/tvm/blob/main/src/tir/analysis/control_flow_graph.h), the additional formalism and reliability proposed here would be very useful.

Thanks, @Lunderberg. What you mentioned is a great analysis tool, and most part of its capability is beyond what integer set targets to achieve. It seems to me that data-flow analysis focuses more on global/high-level info and integer set focuses more on local info inside iteration. They are expected to benefit the overall analysis tools together.

**Comment by Hzfengsy** [comment]
Thanks for everyone's input. We are going to merge in 24 hours if there are no additional comments.

**Comment by Hzfengsy** [comment]
Thanks, @multiverstack-intellif for the proposal and @tqchen @vinx13 's review.

**Pull request merged**
