### PR TITLE
[RFC][WEB][AUTO TVM]add web assembly autotvm support

### PR DESCRIPTION
**Pull request by xiebaiyuan**
Add web assembly autotvm support for TVM, 
The related pull request will be pushed soon, which will be finished in a week.

### CODE REVIEW

**Comment by xiebaiyuan** [comment]
@tqchen @junrushao1994

**Comment by tqchen** [comment]
Thanks @xiebaiyuan . 

On the wasm binary pulling. We might be able to reuse 
 the new RPC session constructor(via websocket)  that directly reconstructs from the wasm binary, so file exchange may not be needed https://github.com/apache/tvm/blob/main/web/tests/python/webgpu_rpc_test.py#L59

Would that eliminate the need of directory based exchange?

**Comment by xiebaiyuan** [comment]
@tqchen We've thought it over in recent days, and will use websocket to transfer intermediate products. The rfc will be updated in a few days.

**Comment by areusch** [comment]
hey @xiebaiyuan you might take a look at the microTVM autoTVM infrastructure--it should be reusable for wasm. 
- https://tvm.apache.org/docs/tutorials/micro/micro_autotune.html#sphx-glr-tutorials-micro-micro-autotune-py
- https://github.com/apache/tvm/blob/main/python/tvm/micro/build.py#L67

**Comment by xiebaiyuan** [comment]
> hey @xiebaiyuan you might take a look at the microTVM autoTVM infrastructure--it should be reusable for wasm.
> 
> * https://tvm.apache.org/docs/tutorials/micro/micro_autotune.html#sphx-glr-tutorials-micro-micro-autotune-py
> * https://github.com/apache/tvm/blob/main/python/tvm/micro/build.py#L67

@areusch  thanks ~~ i will look in it

**Comment by areusch** [comment]
hey @xiebaiyuan just combing through old RFCs. are you guys still working on this one?

**Comment by areusch** [comment]
closing due to lack of response

**Pull request closed without merging**
